### ISSUE TITLE
Replace microbundle with plain rollup usage?

### ISSUE THREAD

**Issue by henrist** [capralifecycle/jslib-baseline#7]
Tested this in https://github.com/capraconsulting/validation-utils-js/commit/89ddc3618885be7e6462f1dca9bb8340e89aee0d

I think microbundle is a bit too bloated, and it has a very large dependency tree. This is reasonable as it attempts to "solve everything".

Microbundle uses Rollup under the hood, so we might just use that directly instead.

I haven't settled my opinion on this, so leaving this issue open for now.

**Comment by oyvindym** [comment]
Added in https://github.com/capraconsulting/jslib-baseline/commit/a133fe3332723cec467e66af32cc91e7db917ee5
