### ISSUE TITLE
Use semantic-release to automate release process

### ISSUE THREAD

**Issue by henrist** [capralifecycle/jslib-baseline#8]
[`semantic-release`](https://github.com/semantic-release/semantic-release) can ease our release process by automating the releases based on the Git commit messages. This way we can enable automatic releases in our CI-pipeline, so that pushes on `master` will trigger a new release.

Using this also means we need to write "proper" Git commit messages, as explained in the docs in the link above.

As of currently, `semantic-release` depends on `npm` which itself depends on an old version of `node-gyp`, which itself depends on dependencies having vulnerabilities. Introducing this now will cause security alerts we have to ignore, which isn't a good thing. So we might want to wait a bit to see if `npm` can get updated some time soon, to avoid this.

**Comment by oyvindym** [comment]
Added in https://github.com/capraconsulting/jslib-baseline/commit/a133fe3332723cec467e66af32cc91e7db917ee5
